# Generated by Django 3.2.25 on 2024-07-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymous_likes',
            field=models.IntegerField(default=0),
        ),
    ]
