# Generated by Django 3.2.25 on 2024-08-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20240807_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_course_material',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
