# Generated by Django 4.2.9 on 2024-08-27 20:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20240821_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='favicon.466a1a490666', max_length=255, verbose_name='image'),
        ),
    ]
