# Generated by Django 4.2.9 on 2024-08-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/favicon.png', upload_to='images/'),
        ),
    ]
